spring.application.name=Git Made Easy

spring.datasource.url=jdbc:h2:mem:gitmadeeasy
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.username=23629028@stu.mmu.ac.uk
spring.datasource.password=MyPassword123'