spring.application.name=Git Made Easy
spring.profiles.default=dev

# Use the specified port environment variable, otherwise default to port 8080
server.port=${PORT:8080}

# Load the environment variables from the .env file, ignoring the file if missing
spring.config.import=optional:dotenv:.env