# If true, lessons will be loaded from one or more JSON files, paths specified underneath
# If false, the application will load default lessons data
seed.from-file=false

# Multiple files allowed (comma-separated)
# Supports:
#  -   classpath:seed/lessons.json
#  -   file:/absolute/path/to/lessons.json
#  -   ./relative/path/lessons.json
#  -   lessons.json
seed.file-path=classpath:seed/lessons.json

# If true, users are required to verify their email before login
auth.require-email-verification=true

# JWT Secret
jwt.secret=${JWT_SECRET}

# Firebase API and Service Account Keys
firebase.service-account=${FIREBASE_SERVICE_ACCOUNT_JSON:classpath:service-account.json}
firebase.api-key=AIzaSyDwSj1TUb7KL1bmhSNVSdmbaPBTNmPCPA4

# CORS Configuration
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

# SMTP Configuration
smtp.username=${SMTP_USERNAME}
smtp.password=${SMTP_PASSWORD}
smtp.fromEmailAddress=${SMTP_FROM}