spring.application.name=Git Made Easy
spring.profiles.default=dev

# SMTP Email Properties / Settings For Sending Email Verification Link To Users Via SMTP
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=gitmadeeasy.noreply@gmail.com
smtp.password=dqpzypyisxvcbdco
smtp.from=gitmadeeasy.noreply@gmail.com