name: Perform Code Coverage On Backend System With JaCoCo

on:
  pull_request:
    paths:
      - 'backend-server/src/**'
      - '.github/workflows/backend-code-coverage.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend-server/src/**'
      - '.github/workflows/backend-code-coverage.yml'

permissions:
  contents: write
  
jobs:
  perform-backend-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make mvnw Excecutable
        working-directory: backend-server
        run: chmod +x ./mvnw

      - name: Run Maven Verify With JaCoCo
        working-directory: backend-server
        run: ./mvnw verify

      - name: Generate JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: ./backend-server/target/site/jacoco/jacoco.xml
          coverage_report_name: GitMadeEasy-JaCoCo-Code-Coverage-Report
          coverage_report_title: Git Made Easy - JaCoCo Code Coverage Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: true
          minimum_coverage: 80 # can be adapted to the business rules
          fail_below_threshold: false # change to true when business logic implies a minimum coverage to be achieved
          publish_only_summary: false

      - name: Add JaCoCo report to workflow run summary
        if: always()
        run: |
          echo "## 📊 Git Made Easy JaCoCo Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Parameter | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Coverage (%) | **${{ steps.jacoco_reporter.outputs.coverage_percentage }}%** |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Lines Counted | ${{ steps.jacoco_reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Lines Missed | ${{ steps.jacoco_reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
