name: Performing Snyk Scan On Frontend System For Vulnerabilities In Dependencies and Libraries

on:
  pull_request:
    paths:
      - 'frontend-app/**'
      - '.github/workflows/frontend-dependencies-snyk-scan.yml'
  push:
    branches:
      - main
    paths:
      - 'frontend-app/**'
      - '.github/workflows/frontend-dependencies-snyk-scan.yml'

jobs:
  frontend-dependencies-snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Install npm Packages
        working-directory: frontend-app
        run: npm install
        
      - name: Run Snyk Scan For Vulnerabilities In Dependencies And Libraries
        run: snyk test frontend-app --all-projects --sarif-file-output=frontend-dependency-vulnerabilities.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF File Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dependency-vulnerabilities
          path: frontend-dependency-vulnerabilities.sarif

      - name: Upload Dependencies Scan Summary
        run: |
          echo "# Dependencies And Libraries Vulnerabilities Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "## **Total Findings**" >> $GITHUB_STEP_SUMMARY
          echo "**$(jq -r '.runs[0].results | length' frontend-dependency-vulnerabilities.sarif)** Vulnerabilities Detected" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          jq -r '.runs[0].results[] |
            "# \(.ruleId)\n
            **Severity:** \(.level)\n
            **Message:** \(.message.text)\n
            **Affected Package:** \(.locations[]?.logicalLocations[]?.fullyQualifiedName)\n
            **Fix:** \(.fixes[]?.description.text)\n
            "
          ' frontend-dependency-vulnerabilities.sarif >> $GITHUB_STEP_SUMMARY  
